#
# File: https://github.com/data-engineering-helpers/ks-cheat-sheets/blob/main/infrastructure/databricks-apps/nyctaxi-app/resources/database.yml
#
# Lakebase instance and synced table resources
# See:
# * Documentation: https://docs.databricks.com/aws/en/dev-tools/bundles/resources
# * Original file: https://github.com/databricks-solutions/databricks-dab-examples/blob/main/knowledge-base/app-react-lakebase/resources/database.yml
#

resources:
  database_instances:
    trips-app-instance:
      name: lakebase-poc
      capacity: CU_1
  synced_database_tables:
    trips-app-synced-table:
      name: ${var.catalog}.${var.schema}.trips_synced
      database_instance_name: ${resources.database_instances.trips-app-instance.name}
      logical_database_name: trips-app-database
      spec:
        source_table_full_name: ${var.catalog}.${var.schema}.trips
        scheduling_policy: SNAPSHOT
        primary_key_columns:
          - id
