gateways:
  local:
    connection:
      type: spark
      catalog: unity
    state_connection:
      type: duckdb
      database: db.db

physical_schema_mapping:
  '^default$': default

environment_suffix_target: table

default_gateway: local

model_defaults:
  dialect: spark
  start: 2024-12-30

