#
# Ref: https://stackoverflow.com/a/76748564/798053
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db

spec:
  selector:
    matchLabels:
      app: db

  serviceName: "db"
  template:
    metadata:
      labels:
        app: db
    spec:

      initContainers:
        - name: db-init    # using root, change permissions to not use root in main container
          image: postgres
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 999  # postgres user in container
            runAsGroup: 999
          resources:
            limits:
              memory: 200Mi
              cpu: 300m
            requests:
              memory: 100Mi
              cpu: 100m
          command: 
            - 'sh'
            - '-c'
            - |
              chown -R 999:999 /var/lib/postgresql/data
              
          volumeMounts:
            - name:  db
              mountPath: /var/lib/postgresql/data


      containers:
      - name: db
        image: postgres
        securityContext:
          runAsNonRoot: true
          runAsUser: 999  # postgres user in container
          runAsGroup: 999
          allowPrivilegeEscalation: false

        resources:
          limits:
            memory: 200Mi
            cpu: 300m
          requests:
            memory: 100Mi
            cpu: 100m
          
        envFrom:
          - secretRef:
             name: db-env

        ports:
        - containerPort: 5432
          name: db

        volumeMounts:
        - name: db
          mountPath: /var/lib/postgresql/data

        startupProbe:
          tcpSocket:
            port: db
          initialDelaySeconds: 5
          periodSeconds: 2
          failureThreshold: 15

        readinessProbe:
          exec:
            command:
              - bash 
              - '-c'
              - >
                psql -h localhost -U "${POSTGRES_USER}" -c 'select 1'

          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 5

        livenessProbe:
          exec:
            command:
              - bash 
              - '-c'
              - >
                psql -h localhost -U "${POSTGRES_USER}" -c 'select 1'

          initialDelaySeconds: 5
          periodSeconds: 10

      volumes:
    
        - name: db
          emptyDir: {}
