apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: nginx
    image: nginxinc/nginx-unprivileged
    securityContext:
      allowPrivilegeEscalation: false
    resources:
      limits:
        memory: 200Mi
        cpu: 300m
      requests:
        memory: 100Mi
        cpu: 100m
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  hostNetwork: false
  dnsPolicy: Default

